### PR TITLE
JBPM-6338: [Lienzo] Text wrapping: Pluggable line splitter

### PR DESCRIPTION
**Pull request by manstis**
See See https://issues.jboss.org/browse/JBPM-6338

This is the accompanying tests.

### CODE REVIEW

**Comment by manstis** [comment]
@Christopher-Chianelli FYI and comment.

**Review by jomarko — APPROVED** [review]
Very nice coverage @manstis ! please just see my two comments in the PR ahome-it/lienzo-core#187 with real changes.

**Comment by manstis** [comment]
@SprocketNYC Thanks for merging https://github.com/ahome-it/lienzo-core/pull/187

This PR contains tests for that what you have merged and should probably accompany it.

**Review by romartin — APPROVED** [review]

**Comment by romartin** [comment]
**NOTE** This PR depends on `lienzo-core 2.0.292-RELEASE`

**Comment by romartin** [comment]
Rebased and merged: a44c612dc0476b823b04726140602d5823789882

**Pull request closed without merging**
